version: "2"
services:
    node:
        container_name: projet-web
        build: .
        restart: always
        command: npm run start
        user: "node"
        environment:
            - NODE_ENV=production
        ports:
            - 8080:8080
